name: crewmeister_frontend_coding_challenge
description: "Crewmeister Frontend Coding Challenge"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  test: ^1.25.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true